# 예외 처리
### throws를 사용한 예외 처리
- try catch 구문을 사용하지 않고, 메소드 선언부에 throws 키워드를 선언하여 예외를 처리한다.
```
public void fileIn(String path) throws IOException  {}
```
- 예외가 발생한 메소드에서 예외처리를 진행하지 않고, 이 메소드를 호출한 곳에서 예외를 처리한다.
- main()(메인 함수)에서 throws를 사용하면 가상머신(JVM)에서 처리된다.

### try{} catch(){} 구문을 사용한 예외 처리
```
try {
  // 실행할 구문
} catch(Exception e)  { // 발생하는 Exception을 안에 적어준다.
  // 에러가 발생하는 경우 처리해야 하는 구문
} finally {
  // 예외의 발생여부와 상관없이 무조건 실행되는 구문
}
```
- 다중 예외 처리   
  + 예외의 가장 상위 Class인 Exception Class의 경우 가장 마지막 catch문에 위치해야 한다.
  + 만일 가장 상단의 catch문에 Exception을 선언하는 경우 그 하위에는 Unreachable catch block이라는 에러 문구가 발생한다.
```
// 정상적인 경우
try {
  ~~~
} catch(IOException ioe) {
  ~~~
} catch(ClassNotFoundException cnfe) {
  ~~~
} catch(Exception e) {
  ~~~
}
// Exception Class를 가장 상단의 catch문에 선언한 경우
try {
  ~~~
} catch(Exception e) {
  ~~~
} catch(ClassNotFoundException cnfe) {  // Unreachable catch block for ClassNotFoundException.
  ~~~
} catch(IOException ioe) {    // Unreachable catch block for IOException.
  ~~~
}
```
- 사용자 정의 예외
  + JDK에서 제공하는 Exception Class외에 사용자가 필요에 의해 Exception Class를 정의하여 사용한다.
  + Exception Class를 상속받아 사용자가 정의하는 Exception Class를 생성할 수 있다. 
  ```
    public class IDFormatException extends Exception  {
      public IDFormatException(String message)  {
        super(message);
      }
    }
    
    public class IDFormatTest {
      public void setUserID(String userId) throws IDFormatException {
        if (userId == null) {
          throw new IDFormatException("ID는 null일 수 없습니다.")
        } else if(userId.length() < 8 || userId.length > 20)  }
          throw new IDFormatException("ID는 8자 이상 20자 이하여야 합니다.")
        }
        
        this.userId = userId;
      }
      
      ~~~
    }
  ```
